# Generated by Django 5.0.7 on 2025-08-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_approved_by_alter_user_last_login_and_more'),
    ]

    operations = [
        # Django가 올바른 데이터베이스 스키마를 인식하도록 함
        migrations.RunSQL(
            "SELECT 1",  # 더미 SQL (실제로는 아무것도 하지 않음)
            reverse_sql="SELECT 1"
        ),
    ]
