# Generated by Django 5.0.7 on 2025-08-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 상태'),
        ),
        migrations.AddField(
            model_name='domain',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='담당자 연락처'),
        ),
    ]
