# Generated by Django 5.0.7 on 2025-08-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_domain_is_active_domain_owner_contact'),
    ]

    operations = [
    ]
